apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resume-uploads-pvc
  namespace: prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: oci-bv
  resources:
    requests:
      storage: 5Gi
