# k8s/prod/secret.yml

apiVersion: v1
kind: Secret
metadata:
  name: resume-analyzer-secret
  namespace: prod
type: Opaque
data:
  DB_URL: ${DB_URL_BASE64}
  DB_USERNAME: ${DB_USERNAME_BASE64}
  DB_PASSWORD: ${DB_PASSWORD_BASE64}
  REDIS_PASSWORD: ${REDIS_PASSWORD_BASE64}
  RABBITMQ_USERNAME: ${RABBITMQ_USERNAME_BASE64}
  RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD_BASE64}
  JWT_SECRET: ${JWT_SECRET_BASE64}
  AI_API_KEY: ${AI_API_KEY_BASE64}
  OCI_USER_OCID: ${OCI_USER_OCID_BASE64}
  OCI_TENANCY_OCID: ${OCI_TENANCY_OCID_BASE64}
  OCI_FINGERPRINT: ${OCI_FINGERPRINT_BASE64}
  OCI_PRIVATE_KEY: ${OCI_PRIVATE_KEY_BASE64}
  GRAFANA_USER: ${GRAFANA_USER_BASE64}
  GRAFANA_PASSWORD: ${GRAFANA_PASSWORD_BASE64}